language: node_js
node_js:
  - "8.4"
sudo: required
script:
  - npm t
  - npm i react-native-cli -g
  - react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios
  - react-native bundle --dev false --platform android --entry-file index.android.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug 
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - build-tools-23.0.3
          - build-tools-25.0.1
        licenses:
          - '.+'
    - language: objective-c
      os: osx
      osx_image: xcode8.3
